# Architettura
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := deen

# === PARAMETRI ESATTI dalla TWRP funzionante ===
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_TAGS_OFFSET := 0x00000100

# Kernel corretto (zImage compresso)
BOARD_KERNEL_IMAGE_NAME := zImage
TARGET_PREBUILT_KERNEL := device/motorola/deen/kernel

# Cmdline ESATTA dalla TWRP funzionante
BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci androidboot.hab.product=deen androidboot.selinux=permissive androidboot.fastboot=1 buildvariant=userdebug


BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_MKBOOTIMG_ARGS := --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET)

# Partizioni (valori approssimativi - verifica con il tuo dispositivo)
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864  # 64MB
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864  # 64MB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2684354560  # 2.5GB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 25765043200  # ~24GB
BOARD_FLASH_BLOCK_SIZE := 131072  # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_VENDORIMAGE_PARTITION_SIZE := 536870912  # 512MB

# Filesystem
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

# Recovery
BOARD_USES_RECOVERY_AS_BOOT := true
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_RECOVERY_FSTAB := device/motorola/deen/recovery.fstab

# TWRP
TW_THEME := portrait_hdpi
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_SUPERSU := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INCLUDE_CRYPTO := true
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 128
TW_NO_SCREEN_BLANK := true
TW_NO_USB_STORAGE := false

# A/B
AB_OTA_UPDATER := true
BOARD_HASH_TYPE := sha256

# Platform
BOARD_PLATFORM := msm8953
TARGET_BOARD_PLATFORM := msm8953
TARGET_BOARD_SUFFIX := _64

# Aggiungi queste linee alla fine del tuo BoardConfig.mk
TARGET_COPY_OUT_VENDOR := vendor
TARGET_RECOVERY_QCOM_RTC_FIX := true
TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_64_BIT_APPS := true

# Importante per TWRP theme
# Display settings - QUESTE SONO CRITICHE
TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1520
DEVICE_SCREEN_WIDTH := 720
DEVICE_SCREEN_HEIGHT := 1520
TW_THEME := portrait_hdpi
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

# Riduci dimensione TWRP
TW_EXCLUDE_NANO := true
TW_EXCLUDE_BASH := true
TW_EXCLUDE_PYTHON := true
TW_EXCLUDE_TZDATA := true
TW_EXCLUDE_FORCE_ENCRYPTION := true
TW_NO_EXFAT := true
TW_NO_EXFAT_FUSE := trueTW_EXCLUDE_HWUI := true
